var js_lang = {	
	errEnterKeywords: 'Поиск товаров', 
	errWrongEmail: 'Реактивный Email.', 
	errPassword: 'Ваш пароль должен содержать не менее 5 знаков.', 
	errNotAgree: 'Вы не согласны с Doreenbeads.com правилами и условиями', 
	errEmailContain: 'Ваш электронный адрес должен содержать не менее 6 знаков.', 
	errConfirmPassword: 'Пароль Подтверждения должен совпадать с Паролем.', 
	errEnter2Char: 'введите 2 знака по крайней мере', 
	ReviewTips: 'Пожалуйста, добавьте еще ​​несколько слов в ваши комментарии, который должен иметь по крайней мере 1 знак.', 
	InputValidCode: 'Пожалуйста, введите правилмный подверждающий код!', 
	EnterEmailAddress: 'введите ваш адрес электронной почты', 
	CheckEmailAddress: 'пожалуйста, проверьте ваш адрес электронной почты', 
	EnterName: 'введите ваше имя', 
	EnterFriendEmail: "Пожалуйста, введите адрес электронной почты вашего друга", 
	CheckFriendEmail: "Пожалуйста, проверьте адрес электронной почты вашего друга, он должен выглядеть так, как email@hotmail.com", 
	CheckYourEmail: 'Пожалуйста, проверьте адрес электронной почты, он должен выглядеть так, как email@hotmail.com', 
	EnterFriendName: "Пожалуйста, введите имя вашего друга", 
	EnterFirstName: 'Пожалуйста, введите своё имя', 
	EnterLastName: 'Пожалуйста, введите вашу фамилию', 
	ReviewLevel: ["(Бедный)","(Равный)","(Средний)","(Хороший)","(Отличный)"], 
	ChooseRating: '*Пожалуйста, выберите рейтинг для этого товара', 
	SuccessAddcart: 'Товар (ы) добавлен(ы) успешно в Вашу корзину!<br/><a href="index.php?main_page=shopping_cart">Смотреть Вашу корзину</a>', 
	TextUpdate: 'Обновлять', 
	TextSuccess: 'успешно',
	QtyAlreadyInCart: 'Количество Уже Было В Корзине: ', 
	SuccessAddWishlist: 'Товар (ы) добавлено(ы) успешно в список пожеланий!<br/><a href="index.php?main_page=wishlist">Смотреть список пожеланий товаров</a>', 
	HasInWishlist: 'Этот продукт был в списке пожеланий.<br/><a href="index.php?main_page=wishlist">Смотреть список пожеланий товаров</a>', 
	LoginToOperation: 'Пожалуйста, войдите, чтобы оператировать <a href="index.php?main_page=login">Login</a>', 
	SuccessSubscribed: 'Поздравляем! Вы успешно подписались на это уведомление пополнения запасов продуктов. Электронное письмо со ссылкой данного продукта будет отправлено вам как только запасы склада доступены.', 
	EnterRightQty: 'Пожалуйста, введите правильное количество!', 
	QtyInCart: 'Количество в корзину', 
	ErrorPleaseKeyword: 'Пожалуйста, введите ключевые слова или артикул.',
	ENTER_PASSWORD_PROMPT : 'Пожалуйста введите ваш пароль.',
	CHECKOUT_ZIP_CODE_ERROR:'Проверьте, пожалуйста, свой почтовый индекс, правильный формат:',
	TEXT_OR:'или',
	CartAreYouSureDelete: 'Вы уверены, что удалить этот товар?',
	CartAreYouSureDeleteAll: 'Подтверждаете ли вы удалить выбранные элементы в корзине?',
	CartJsWrongNumber: 'Неправильный артикул. Чтобы продолжать, Вы должны удалить этот товара из списка.',
	CartWrongNumber: 'Неправильный артикул.',
	CartJsNoStock: 'Нет запасов на складе. Чтобы продолжать, Вам надо удалять этот артикул из списка.',
	CartNoStock: 'Нет в наличии.',
	CartQuickAddWrong: 'Извините, некоторые товары были не доступны. Пожалуйста, удаляйте неправильный артикул / количество',
	CartQuickAddEmpty: 'Пожалуйста, введите по крайней мере один артикул и количество товара',
	TEXT_CHECK_URL:'Введенный вами контент содержит нелегальные ссылки. Пожалуйста, исправьте это.',
	TextProcess: 'обработка...',	
	TEXT_SURE_DELETE_ADDRESS: 'Вы действительно хотите удалить этот адрес',
	TEXT_ENTER_A_ADDRESS: 'Введите новый адрес',
	TEXT_EDIT_ADDRESS: 'Редактировать информацию адреса',
	TEXT_PLEASEENTER_CHARLEAST_2: 'Пожалуйста, введите 1 продукты по крайней мере.',
	TEXT_PLEASEENTER_CHARLEAST_5: 'Пожалуйста, введите 5 продукты по крайней мере.',
	TEXT_PLEASEENTER_CHARLEAST_3: 'Пожалуйста, введите 3 продукты по крайней мере.',
	TEXT_PLEASEENTER_RIGHTSTATE: 'Пожалуйста, введите правильную  Страну / провинцию / область.',
	TextYes:'Yes',
	TextNo:'No',
	
	WEBSITE_ADDRESS_FORMAT : 'Формат адреса веб-сайта неверен, пожалуйста, заполните правильный веб-адрес.',
	errWrongEmail : 'Правилен ли ваш адрес электронной почты ?Он должен как минимум содержать 6 символов.Пожалуйста, попробуйте еще раз.',
	TEXT_ALREADY_INCART : 'Этот товар уже в корзине. Вы могли изменить количество прямо в корзине.',
	TEXT_CANT_ADDCART : 'Вы не можете прямо добавить товары в корзину теперь. Пожалуйста, свяжитесь с нами по любым вопросам . sale_ru@doreenbeads.com.',
	TEXT_ADD_TO_CART_SUCCESS : 'Добавлять в корзину успешно!<br/><a href="index.php?main_page=shopping_cart">Смотреть корзину</a> / <a href="javascript:void(0);" class="successtips_collect_close">Close</a>',
	'CHECKOUT_ADDRESS_BOOK_PLEASE_ENTER' : 'Пожалуйста,введите',
	'CHECKOUT_ADDRESS_BOOK_CHARACTERS_AT_LEAST' : ' символов как минимум.',
	'CHECKOUT_ADDRESS_BOOK_RIGHT_STATE' : 'Пожалуйста, введите правильный штат.',
	'TEXT_ENTER_A_COUPON_CODE':'Eввозите код купона',

	'TEXT_ACCONT_ENTER_YNAME_ERROR': 'Пожалуйста, введите 1 символа по крайней мере.',
	'TEXT_ACCONT_ENTER_AMOUNT' : 'Пожалуйста, введите сумму.',
	'TEXT_ACCONT_ENTER_AMOUNT_TYPE' : 'Сумма должна быть цифром',
	'TEXT_ACCONT_ENTER_PAYMNET_DATE' : 'Пожалуйста, введите дату оплаты.',
	'TEXT_ACCONT_ENTER_FIRST_NAME' : 'Пожалуйста,введите имя.',
	'TEXT_ACCONT_ENTER_LAST_NAME' : 'Пожалуйста,введите фамилию.',
	'TEXT_ACCONT_ENTER_ADDRESS' : 'Пожалуйста,Введите адрес.',
	'TEXT_ACCONT_ENTER_CONTROL_NO' : 'Пожалуйста,введите контрольный номер.',
	'TEXT_ACCONT_ENTER_CONTROL_NO_TYPE' : 'Контрольный номер должен быть цифром',
	'TEXT_ACCONT_ENTER_CONTROL_NO_10' : 'Контрольный номер должен быть 10 цифром',
	'TEXT_ACCONT_ENTER_CONTROL_NO_8' : 'Контрольный номер должен быть 8 цифром',
	'TEXT_ACCONT_ENTER_REMITTER' : 'Пожалуйста напишите "полное имя плательщика" на английском.',
	'TEXT_ACCONT_ENTER_PAYEE' : 'Пожалуйста, введите полное имя получателя платежа.',
	'TEXT_ACCONT_ENTER_COUNTRY' : 'Пожалуйста, введите вашу страну.',
	
	TEXT_CONFIRM_PASSWORD:'Не забудьте повторно ввести пароль!',
	ENTRY_EMAIL_ADDRESS_CHECK_ERROR:'Извините!Наша система не понимает ваш адрес  email .Пожалуйста, попробуйте еще раз.',
	WrongEmail:'Правилен ли ваш адрес электронной почты ?Он должен как минимум содержать6 символов.Пожалуйста, попробуйте еще раз.',
	RegEmail:'Неправильный адрес электронной почты, пожалуйста, укажите правильный адрес электронной почты.',
	WrongPassword : 'Это должно быть не менее 5 символов (должны содержать буквы и цифры).',
	WrongLastName:'Пожалуйста, введите вашу фамилию (не менее 1 символа).',
	WrongFirstName:'Пожалуйста, введите ваше имя (не менее 1 символа).',
	WrongPwdConf:'Пароль Подтверждения должен совпадать с паролем.',
	NotAgreeTC:'Вы не согласны с Doreenbeads.com Правила и Условия',
	CheckEmail:'Входите ваш адрес электронной почты.!',
	CheckValidate:'Введите правый действительный код, пожалуйста !',	
	CheckTestimonialContent:'Пожалуйста, добавьте еще ​​несколько слов в ваши комментарии, который должен иметь по крайней мере 1 знак.',
	TEXT_ENTER_BIRTHDAY_ERROR:"Укажите действительную дату рождения.",
	TEXT_ENTER_BIRTHDAY_OVER_DATE:"Дата рождения не может предшествовать сегодняшнему дню.",

	/*contact us*/
	TEXT_NAME_EMPTY :'введите своё имя, пожалуйста!',
	TEXT_NAME_SHORT :'Your name must be at least 2 characters',
	TEXT_EMAIL_EMPTY :'Входите ваш адрес электронной почты. Спасибо!',
	TEXT_MESSAGE_EMPTY :'Пожалуйста, введите ваше сообщение!',
	TEXT_AUTH_CODE_ERROR : 'Пожалуйста, введите правильный код!',
	
    /*affiliate program*/
    TEXT_AFFILIATE_ERROR1 :'Please enter your email or telephone number',
	TEXT_AFFILIATE_ERROR2 :'Please enter your paypal account',
    TEXT_SUCCESS :'Successfully copied',
	
	'TEXT_SUBSCRIBE_FOR': 'Адрес Почты',
	'TEXT_ENTER_YOUR_EMAIL_ADDRESS':'Адрес Почты',
	'TEXT_EMAIL_FORMAT': 'Реактивный Email.',
	'TEXT_SUBSCRIBE_SUCCESS': 'Thanks for subscribing!',
	'TEXT_UPDATE': 'Обновлять',
	reviewlevel : ["(Poor)","(Fair)","(Average)","(Good)","(Excellent)"],
	
	'TEXT_EMAIL_WRONG': 'Your email address does not appear to be valid, please try again',
	'TEXT_FNAME_CANNOT_EMPTY': 'Ваше имя не должно быть пустым',
	'TEXT_LNAME_CANNOT_EMPTY': 'Ваша фамилия не должна быть пустой.',
	'TEXT_QUESTION_CANNOT_EMPTY': 'Ваш вопрос не должен быть пустым.',
	'ENTRY_FL_NAME_SAME_ERROR': 'Фамилия совпадает с именем. Пожалуйста, измените его.',
	'TEXT_OTHERS':'Другие',
	'TEXT_FILL_IN_CURRENCY_YOU_USED':'Please fill in the currency you used.',
	/*address line 1 2 same error*/
	'ENTRY_FS_ADDRESS_SAME_ERROR':'Мы заметили, что ваш Адрес строки 2 такой же, как Адресная строка 1, пожалуйста, переписывайте Адресную строку 2 или просто оставляйте её пустой.',
	'TEXT_CART_MOVE_TO_WISHLIST':'в список пожеланий',
	'TEXT_INPUT_RIGHT_CODE':'Введите правый действительный код, пожалуйста !',

	// account edit
	'TEXT_LANG_YEAR': 'Года',
	'TEXT_LANG_MONTH': 'Месяц',
	'TEXT_LANG_DAY': 'День',

	'TEXT_BACKORDER': 'Предзаказ',
	'TEXT_ADD_TO_CART': 'Добавлять в корзину',

	'TEXT_ADDED': 'Добавлено',
	'TEXT_CANNOT_ADDED': 'Продукт недействителен.',

	'TEXT_WISHLIST': 'Список пожеланий',
};