<?php
define ( 'MODULE_SHIPPING_ZYUPS_TEXT_TITLE', 'UPS（ZYエージェント）' );
define ( 'MODULE_SHIPPING_ZYUPS_TEXT_DESCRIPTION', 'UPS（ZYエージェント）（6-8営業日ワールドワイド）' );
define ( 'MODULE_SHIPPING_ZYUPS_TEXT_WAY', TEXT_SHIPPING_TO );
define ( 'MODULE_SHIPPING_ZYUPS_TEXT_UNITS', TEXT_WEIGHT_KG );
define ( 'MODULE_SHIPPING_ZYUPS_INVALID_ZONE', TEXT_NO_SHIPPING_WORDS );
define ( 'MODULE_SHIPPING_ZYUPS_UNDEFINED_RATE', TEXT_SHIPPING_CANNOT_ARRIVE );
define ( 'MODULE_SHIPPING_ZYUPS_NOTE', sprintf ( TEXT_SHIPPING_NOTE, 'ZYUPS' ) );
define ( 'MODULE_SHIPPING_NORMAL_ZYUPS_NOTE', sprintf ( TEXT_SHIPPING_NOTE, 'ZYUPS' ) );
define ( 'MODULE_SHIPPING_ZYUPS_TEXT_ERROR', TEXT_ERROR_TO_CONTACT_US );
define ( 'MODULE_SHIPPING_NORMAL_ZYUPS_VOLUME_NOTE', TEXT_SHIPPING_FEE . ',
			<a href="' . HTTP_SERVER . '/page.html?chapter=0&id=92" target="_blank">' . TEXT_CLICK_HERE_FOR_MORE . '.</a>' );
?>