<?php
define('MODULE_SHIPPING_YWFEDEX_TEXT_TITLE', 'YW-FedEx');
define('MODULE_SHIPPING_YWFEDEX_TEXT_DESCRIPTION', '(3-5 días laborales para el envío% s)');
define('MODULE_SHIPPING_YWFEDEX_TEXT_WAY', TEXT_SHIPPING_TO);
define('MODULE_SHIPPING_YWFEDEX_TEXT_UNITS', TEXT_WEIGHT_KG);
define('MODULE_SHIPPING_YWFEDEX_INVALID_ZONE', TEXT_NO_SHIPPING_WORDS);
define('MODULE_SHIPPING_YWFEDEX_UNDEFINED_RATE', TEXT_SHIPPING_CANNOT_ARRIVE);
define('MODULE_SHIPPING_YWFEDEX_NOTE', sprintf(TEXT_SHIPPING_NOTE,'YWFEDEX'));
define('MODULE_SHIPPING_NORMAL_YWFEDEX_NOTE', sprintf(TEXT_SHIPPING_NOTE,'FEDEX'));
define('MODULE_SHIPPING_YWFEDEX_TEXT_ERROR', TEXT_ERROR_TO_CONTACT_US);
define('MODULE_SHIPPING_NORMAL_YWFEDEX_VOLUME_NOTE', TEXT_SHIPPING_FEE.', 
 			<a href="'.HTTP_SERVER.'/page.html?chapter=0&id=92" target="_blank">'.TEXT_CLICK_HERE_FOR_MORE.'.</a>');
define('TEXT_BOX_NUMBER', ', en %s cajas');
?>