<?php
define('MODULE_PAYMENT_WESTERNUNION_TEXT_SENDER', 'Remitente');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_MCTN', 'MTCN:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_AMOUNT', 'Monto:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_CURRENCY', 'Moneda:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_FIRST_NAME', 'Nombre:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_LAST_NAME', 'Apellido:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_ADDRESS', 'Dirección:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_ZIP', 'Código Postal:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_CITY', 'Ciudad:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_COUNTRY', 'País:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_PHONE', 'Teléfono:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_QUESTION', 'Pregunta:');
define('MODULE_PAYMENT_WESTERNUNION_ENTRY_ANSWER', 'Respuesta:');
define('MODULE_PAYMENT_GCCREDITCARD_RECEIVER_FIRST_NAME', 'GCCC');
define('MODULE_PAYMENT_WESTERNUNION_RECEIVER_LAST_NAME', '');
define('MODULE_PAYMENT_WESTERNUNION_RECEIVER_ADDRESS', '');
define('MODULE_PAYMENT_WESTERNUNION_RECEIVER_ZIP', '');
define('MODULE_PAYMENT_WESTERNUNION_RECEIVER_CITY', '');
define('MODULE_PAYMENT_WESTERNUNION_RECEIVER_COUNTRY', '');
define('MODULE_PAYMENT_WESTERNUNION_RECEIVER_PHONE', '');
define('MODULE_PAYMENT_GCCREDITCARD_TEXT_HEAD', 'Tarjeta de Crédito (Via Global Collect)');
define('MODULE_PAYMENT_WESTERNUNION_TEXT_END', '<br /><div style="clear:both; padding-bottom:10px;"><span style="color:#F47504"><strong>Asegúrese de leer esta importancia nota antes de realizar el pago.</strong></span> <a href="http://www.dreams-crafts.net/page.html?chapter=0&id=95" target="_blank">Haga clic aquí>></a></div>');
?>