<?php
define ( 'MODULE_SHIPPING_GBLINE_TEXT_TITLE', 'イギリス速達サービス' );
define ( 'MODULE_SHIPPING_GBLINE_TEXT_DESCRIPTION', 'イギリス速達サービス' );
define ( 'MODULE_SHIPPING_GBLINE_TEXT_WAY', TEXT_SHIPPING_TO );
define ( 'MODULE_SHIPPING_GBLINE_TEXT_UNITS', TEXT_WEIGHT_KG );
define ( 'MODULE_SHIPPING_GBLINE_INVALID_ZONE', TEXT_NO_SHIPPING_WORDS );
define ( 'MODULE_SHIPPING_GBLINE_UNDEFINED_RATE', TEXT_SHIPPING_CANNOT_ARRIVE );
define ( 'MODULE_SHIPPING_GBLINE_VOLUME_NOTE', TEXT_SHIPPING_FEE . ',
				<a href="' . HTTP_SERVER . '/page.html?chapter=0&id=92" target="_blank">' . TEXT_CLICK_HERE_FOR_MORE . '.</a>' );
define ( 'MODULE_SHIPPING_UKLINE_REMOTE_AREA_NOTE', 'ご注意事項：遠隔地へ配達するために英国の事業者から必要な追加料金を要求されます。' );
?>