<?php
define ( 'MODULE_PAYMENT_MONEYGRAM_ENTRY_FIRST_NAME', '名前： ' );
define ( 'MODULE_PAYMENT_MONEYGRAM_ENTRY_LAST_NAME', '苗字： ' );
define ( 'MODULE_PAYMENT_MONEYGRAM_ENTRY_ADDRESS', 'アドレス： ' );
define ( 'MODULE_PAYMENT_MONEYGRAM_ENTRY_ZIP', '郵便番号： ' );
define ( 'MODULE_PAYMENT_MONEYGRAM_ENTRY_CITY', '都市： ' );
define ( 'MODULE_PAYMENT_MONEYGRAM_ENTRY_COUNTRY', '国名： ' );
define ( 'MODULE_PAYMENT_MONEYGRAM_ENTRY_PHONE', '電話番号： ' );

define ( 'MODULE_PAYMENT_MONEYGRAM_ABOUT_INFO', ' ( <a href="' . zen_href_link ( 'page', 'id=236' ) . '" target="_blank">マネーグラムについて &gt;&gt;</a> )' );
define ( 'MODULE_PAYMENT_MONEYGRAM_TEXT_HEAD', '<strong>マネーグラム</strong>' );
define ( 'MODULE_PAYMENT_MONEYGRAM_TEXT_DESCRIPTION', '<br>当社の受取人の情報：<div style="line-height:23px;padding: 8px 0 12px 24px;">' . '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_FIRST_NAME . '</strong><span>' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_FIRST_NAME . '</span></p>' . '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_LAST_NAME . '</strong><span>' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_LAST_NAME . '</span></p>' . '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_ADDRESS . '</strong><span>' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_ADDRESS . '</span></p>' . '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_ZIP . '</strong><span>' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_ZIP . '</span></p>' . '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_CITY . '</strong><span>' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_CITY . '</span></p>' . '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_COUNTRY . '</strong><span>' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_COUNTRY . '</span></p>' . '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_PHONE . '</strong><span>' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_PHONE . "</span></p></div>
  <div class='borderbt'></div>" );

define ( 'MODULE_PAYMENT_MONEYGRAM_TEXT_EMAIL_FOOTER', '<br>当社の受取人情報：<div style="line-height:23px;padding: 8px 0 12px 24px;">' . '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_FIRST_NAME . '</b><span style="color:red">' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_FIRST_NAME . '</span></p>' . '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_LAST_NAME . '</b><span style="color:red">' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_LAST_NAME . '</span></p>' . '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_ADDRESS . '</b><span style="color:red">' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_ADDRESS . '</span></p>' . '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_ZIP . '</b><span style="color:red">' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_ZIP . '</span></p>' . '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_CITY . '</b><span style="color:red">' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_CITY . '</span></p>' . '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_COUNTRY . '</b><span style="color:red">' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_COUNTRY . '</span></p>' . '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_PHONE . '</b><span style="color:red">' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_PHONE . "</span></p></div>" . "<b>お金を送った後、下記の情報を (<a href='mailto:service_jp@8seasons.com'><font style='color:#0000FF;'>service_jp@8seasons.com</font></a>)にメールで送ってください。具体的に正確な情報を下記のようにリストされます：</b><ul style='font-weight: normal;line-height: 22px;padding: 10px 0 14px 24px;'><li style='color:red'>1.8桁の管理番号。</li><li style='color:red'>2.合計金額と貨幣記号。</li><li style='color:red'>3. 国名。</li><li style='color:red'>4. 送金者の氏名（正しいの名前と苗字）</li><li style='color:red'>5. 受取人の氏名（正しいの名前と苗字）</li><li>6.問題がないなら、支払いを行った後、我々にあなたの送金書類の画像を提供してください。</li></ul><p style='color:red'>ご注意事項：支払いを行うときには、情報を確認しなければ、我々はお金を引き出すことができません。</p><p style='margin-top:10px;'>お支払いを受け取ったら、ご注文を処理した後すぐ出荷できます。</p>" );
?>