<?php
define('MODULE_PAYMENT_MONEYGRAM_ENTRY_FIRST_NAME', 'Nombre:');
define('MODULE_PAYMENT_MONEYGRAM_ENTRY_LAST_NAME', 'Apellido:');
define('MODULE_PAYMENT_MONEYGRAM_ENTRY_ADDRESS', 'Dirección:');
define('MODULE_PAYMENT_MONEYGRAM_ENTRY_ZIP', 'Código Postal:');
define('MODULE_PAYMENT_MONEYGRAM_ENTRY_CITY', 'Ciudad :');
define('MODULE_PAYMENT_MONEYGRAM_ENTRY_COUNTRY', 'País :');
define('MODULE_PAYMENT_MONEYGRAM_ENTRY_PHONE', 'Teléfono :');
define('MODULE_PAYMENT_MONEYGRAM_ABOUT_INFO', '( <a href="' .zen_href_link('page','id=236'). '" target="_blank">Sobre Money Gram &gt;&gt;</a> )');
define('MODULE_PAYMENT_MONEYGRAM_TEXT_HEAD', '<strong>Money Gram</strong>');
define('MODULE_PAYMENT_MONEYGRAM_TEXT_DESCRIPTION', '<br>Nuestra Información para Beneficiario:<div style="line-height:23px;padding: 8px 0 12px 24px;">' .  '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_FIRST_NAME . '</strong><span>' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_FIRST_NAME . '</span></p>' .  '<p><strong>' .MODULE_PAYMENT_MONEYGRAM_ENTRY_LAST_NAME . '</strong><span>' .   MODULE_PAYMENT_MONEYGRAM_RECEIVER_LAST_NAME . '</span></p>' .  
   '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_ADDRESS . '</strong><span>' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_ADDRESS . '</span></p>'  .   
   '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_ZIP . '</strong><span>' .   MODULE_PAYMENT_MONEYGRAM_RECEIVER_ZIP . '</span></p>'  .   
   '<p><strong>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_CITY .   '</strong><span>' .  MODULE_PAYMENT_MONEYGRAM_RECEIVER_CITY . '</span></p>'  .  
   '<p><strong>' .  MODULE_PAYMENT_MONEYGRAM_ENTRY_COUNTRY . '</strong><span>' .   MODULE_PAYMENT_MONEYGRAM_RECEIVER_COUNTRY . '</span></p>'  .  
   '<p><strong>' .  MODULE_PAYMENT_MONEYGRAM_ENTRY_PHONE . '</strong><span>' .   MODULE_PAYMENT_MONEYGRAM_RECEIVER_PHONE . "</span></p></div>
   <div class='borderbt'></div>");
define('MODULE_PAYMENT_MONEYGRAM_TEXT_EMAIL_FOOTER', '<br>Nuestra Información para Beneficiario:<div style="line-height:23px;padding: 8px 0 12px 24px;">' .  '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_FIRST_NAME . '</b><span style="color:red">' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_FIRST_NAME . '</span></p>' .  '<p><b>' .MODULE_PAYMENT_MONEYGRAM_ENTRY_LAST_NAME . '</b><span style="color:red">' .   MODULE_PAYMENT_MONEYGRAM_RECEIVER_LAST_NAME . '</span></p>' .  '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_ADDRESS . '</b><span style="color:red">' . MODULE_PAYMENT_MONEYGRAM_RECEIVER_ADDRESS . '</span></p>'  .   '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_ZIP . '</b><span style="color:red">' .   MODULE_PAYMENT_MONEYGRAM_RECEIVER_ZIP . '</span></p>'  .   '<p><b>' . MODULE_PAYMENT_MONEYGRAM_ENTRY_CITY .   '</b><span style="color:red">' .  MODULE_PAYMENT_MONEYGRAM_RECEIVER_CITY . '</span></p>'  .  '<p><b>' .  MODULE_PAYMENT_MONEYGRAM_ENTRY_COUNTRY . '</b><span style="color:red">' .   MODULE_PAYMENT_MONEYGRAM_RECEIVER_COUNTRY . '</span></p>'  .   '<p><b>' .  MODULE_PAYMENT_MONEYGRAM_ENTRY_PHONE . '</b><span style="color:red">' .   MODULE_PAYMENT_MONEYGRAM_RECEIVER_PHONE . "</span></p></div>" . "<b>Después de enviar el dinero, por favor envíenos un correo electrónico a(<a href='mailto:service_es@8seasons.com'><font style='color:#0000FF;'>service_es@8seasons.com</font></a>) con la específica y correcta información como siguiente:</b><ul style='font-weight: normal;line-height: 22px;padding: 10px 0 14px 24px;'><li style='color:red'>1. 8-digits de Control del Número.</li><li style='color:red'>2. Monto Total y Símbolo monetario.</li><li style='color:red'>3. Su País.</li><li style='color:red'>4. Nombre completo del Remitente(incluyendo nombre y apellido en el orden correcto).</li><li style='color:red'>5. Nombre completo del beneficiario (incluyendo nombre y apellido en el orden correcto).</li><li>6. Si está bien, por favor, ofrázcanos la imagen de su documento de remesas depués de realizar el pago.</li></ul><p style='color:red'>Nota: Por favor, asegúrese de que ha escrito la información correcta al hacer el pago, si no, no podríamos retirar el dinero.</p><p style='margin-top:10px;'>Comenzaremos a procesar su pedido y se lo enviaremos inmediatamente en cuanto recibamos el pago.</p>");
?>