<?php
define('MODULE_SHIPPING_EXPRESS_DHL_TEXT_TITLE', 'Express DHL');
define('MODULE_SHIPPING_EXPRESS_DHL_DESCRIPTION_TEXT_DESCRIPTION', 'Express DHL');
define('MODULE_SHIPPING_EXPRESS_DHL_SORT_ORDER', 'Orden de Clasificación');
define('MODULE_SHIPPING_EXPRESS_DHL_CURRENCY', 'Dólar a moneda RMB');
define('MODULE_SHIPPING_EXPRESS_DHL_INVALID_ZONE', TEXT_NO_SHIPPING_WORDS);
define('MODULE_SHIPPING_EXPRESS_DHL_NOTE', sprintf(TEXT_SHIPPING_NOTE,'DHL'));
define('MODULE_SHIPPING_EXPRESS_DHL_VOLUME_NOTE', TEXT_SHIPPING_FEE.', 				<a href="'.HTTP_SERVER.'/page.html?chapter=0&id=92" target="_blank">'.TEXT_CLICK_HERE_FOR_MORE.'.</a>');
?>