<?php
define('NAVBAR_TITLE', 'Facebook- Drehen & Gewinnen');
define('TEXT_SPIN_UNAVAILABLE_COUTRY','Entschuligen Sie bitte, leider ist diese Seite zu Ihren Staaten oder Bereichen nicht erreichbar.');
define('TEXT_SPIN_DATE_ENDED','Oops, diese Drehen und Gewinn Lotterie ging schon zum Ende. Bitte verfolgen Sie unsere Facebook Seite weiter, um die neueste Nachrichten über die nächste Lotterie oder andere Aktivitäten zu bekommen.');
define('TEXT_SPIN_OUTOF_CHANCES','Entschuligen Sie bitte, aber Sie haben schon die Drehungschancen ausgeschöpft. Weiter Uns Folgen und warten auf unsere nächste Promotion.<br/>Mal nachschauen und zufriedene Artikel herausfinden!<br/><div class="center"><a class="stw_btn" href="'.zen_href_link(FILENAME_DEFAULT).'">Weiter Kaufen</a></div>');
define('TEXT_SPIN_OUTOF_CHANCES2', 'Teilen es auf Facebook, um zweite Chance zu bekommen!<br/><div class="center"><a class="stw_btn" href="javascript:void(0)" onclick="fbSharePluginInit()">Teilen</a><a class="stw_btn" href="'.zen_href_link(FILENAME_DEFAULT).'">Weiter Kaufen</a></div>');
define('TEXT_SPIN_DONT_WIN_1ST', 'Oops, Entschuldigung, Sie haben nichts gewonnen.<br/>Teilen es auf Facebook, um zweite Chance zu bekommen!<br/><div class="center"><a class="stw_btn" href="javascript:void(0)" %s>Teilen</a></div>');
define('TEXT_SPIN_DONT_WIN_2ND', 'Oops, Entschuldigung, Sie haben nichts gewonnen.<br/>Mal nachschauen und zufriedene Artikel herausfinden!<br/><div class="center"><a class="stw_btn" href="'.zen_href_link(FILENAME_DEFAULT).'">Weiter Kaufen</a></div>');
define('TEXT_SPIN_COUPON_1ST', 'Herzlich Glückwunsch ! Sie haben <span>USD %s</span> Gutschein gewonnen. Es wurde schon auf Ihr Konto gutgeschrieben. Benutzen Sie ihn innerhalb 20 Tage und teilen das Glück zu Ihren Freunden!<br/>Teilen es auf Facebook, um zweite Chance zu bekommen!<br/><div class="center"><a class="stw_btn" href="javascript:void(0)" %s>Teilen</a><a class="stw_btn" href="'.zen_href_link(FILENAME_MY_COUPON, 'status=1').'">Ihren Gutschein nachschauen</a></div>');
define('TEXT_SPIN_COUPON_2ND', 'Herzlich Glückwunsch ! Sie haben <span>USD %s</span> Gutschein gewonnen. Es wurde schon auf Ihr Konto gutgeschrieben. Benutzen Sie ihn innerhalb 20 Tage und teilen das Glück zu Ihren Freunden!<br/><div class="center"><a class="stw_btn" href="'.zen_href_link(FILENAME_MY_COUPON, 'status=1').'">Ihren Gutschein nachschauen</a></div>');
define('TEXT_SPIN_PRODUCT_1ST', 'Herzlich Glückwunsch ! Sie haben <span>%s</span>. Es wurde schon in Ihrem Warenkorb addiert, bitte <a href="'.zen_href_link(FILENAME_SHOPPING_CART).'">bestätigen</a> Sie mal bei der Bezahlung.<br/>Teilen es auf Facebook, um zweite Chance zu bekommen!<br/><div class="center"><a class="stw_btn" href="javascript:void(0)" %s>Teilen</a><a class="stw_btn" href="'.zen_href_link(FILENAME_DEFAULT).'">Weiter Kaufen</a></div>');
define('TEXT_SPIN_PRODUCT_2ND', 'Herzlich Glückwunsch ! Sie haben <span>%s</span>. Es wurde schon in Ihrem Warenkorb addiert, bitte <a href="'.zen_href_link(FILENAME_SHOPPING_CART).'">bestätigen</a> Sie mal bei der Bezahlung.<br/><div class="center"><a class="stw_btn" href="'.zen_href_link(FILENAME_DEFAULT).'">Weiter Kaufen</a></div>');
define('TEXT_SPIN_PRODUCT_DITSAMPLE', 'DIY Sample Kit');
define('TEXT_SPIN_PRODUCT_SWAROVSKI', 'Swarovski® Rhinestone Set');
define('TEXT_SPIN_PRODUCT_NECKLACE', 'Statement Necklace DIY Kit');
?>