var $lang={
	//errEnterKeywords: 'Введите ключевые слова или артикул', 
	errEnterKeywords: 'Поиск товаров', 
	errWrongEmail: 'Неправильный адрес электронной почты, пожалуйста, укажите правильный адрес электронной почты.',  
	errPassword: 'Это должно быть не менее 5 символов (должны содержать буквы и цифры).', 
	errNotAgree: 'Вы не согласны с Doreenbeads.com правилами и условиями', 
	errEmailContain: 'Правилен ли ваш адрес электронной почты ?Он должен как минимум содержать6 символов.Пожалуйста, попробуйте еще раз.', 
	errRemoteCheck: 'Неверный электронной почты. Пожалуйста заполньте правильную электронную почту.',
	errConfirmPassword: 'Пароль Подтверждения должен совпадать с Паролем.', 
	errEnter2Char: 'введите 1 знака по крайней мере', 
	ReviewTips: 'Пожалуйста, добавьте еще ​​несколько слов в ваши комментарии, который должен иметь по крайней мере 1 знак.', 
	InputValidCode: 'Пожалуйста, введите правилмный подверждающий код!', 
	EnterEmailAddress: 'введите ваш адрес электронной почты', 
	CheckEmailAddress: 'пожалуйста, проверьте ваш адрес электронной почты', 
	EnterName: 'введите ваше имя', 
	EnterFriendEmail: "Пожалуйста, введите адрес электронной почты вашего друга", 
	CheckFriendEmail: "Пожалуйста, проверьте адрес электронной почты вашего друга, он должен выглядеть так, как email@hotmail.com", 
	CheckYourEmail: 'Пожалуйста, проверьте адрес электронной почты, он должен выглядеть так, как email@hotmail.com', 
	EnterFriendName: "Пожалуйста, введите имя вашего друга", 
	EnterFirstName: 'Пожалуйста, введите ваше имя (не менее 1 символа).', 
	EnterLastName: 'Пожалуйста, введите вашу фамилию (не менее 1 символа).', 
	ReviewLevel: ["(Бедный)","(Равный)","(Средний)","(Хороший)","(Отличный)"], 
	ChooseRating: '*Пожалуйста, выберите рейтинг для этого товара', 
	SuccessAddcart: 'Товар (ы) добавлен(ы) успешно в Вашу корзину!<br/><a href="index.php?main_page=shopping_cart">Смотреть Вашу корзину</a>', 
	TextUpdate: 'Обновлять', 
	QtyAlreadyInCart: 'Количество Уже Было В Корзине: ', 
	CartAreYouSureInvaild:'Подтверждаете ли вы опорожнять недопустимых элементов?',
	SuccessAddWishlist: 'Товар (ы) добавлено(ы) успешно в список пожеланий!<br/><a href="index.php?main_page=wishlist">Смотреть список пожеланий товаров</a>', 
	HasInWishlist: 'Этот продукт был в списке пожеланий.<br/><a href="index.php?main_page=wishlist">Смотреть список пожеланий товаров</a>', 
	LoginToOperation: 'Пожалуйста, войдите, чтобы оператировать <a href="index.php?main_page=login">Login</a>', 
	SuccessSubscribed: 'Поздравляем! Вы успешно подписались на это уведомление пополнения запасов продуктов. Электронное письмо со ссылкой данного продукта будет отправлено вам как только запасы склада доступены.', 
	EnterRightQty: 'Пожалуйста, введите правильное количество!', 
	QtyInCart: 'Количество в корзину', 
	ErrorPleaseKeyword: 'Пожалуйста, введите ключевые слова или артикул.',
	ENTER_PASSWORD_PROMPT : 'Пожалуйста введите ваш пароль.',
	TEXT_CONFIRM_PASSWORD : "Не забудьте повторно ввести пароль!",
	CHECKOUT_ZIP_CODE_ERROR:'Проверьте, пожалуйста, свой почтовый индекс, правильный формат:',
	TEXT_OR:'или', 
	CartAreYouSureDelete: 'Вы уверены, что удалить этот товар?',
	CartAreYouSureDeleteAll: 'Подтверждаете ли вы удалить выбранные элементы в корзине?',
	CartJsWrongNumber: 'Неправильный артикул. Чтобы продолжать, Вы должны удалить этот товара из списка.',
	CartWrongNumber: 'Неправильный артикул.',
	CartJsNoStock: 'Нет запасов на складе. Чтобы продолжать, Вам надо удалять этот артикул из списка.',
	CartNoStock: 'Нет в наличии.',
	CartQuickAddWrong: 'Извините, некоторые товары были не доступны. Пожалуйста, удаляйте неправильный артикул / количество',
	CartQuickAddEmpty: 'Пожалуйста, введите по крайней мере один артикул и количество товара',
	
	TextProcess: 'обработка...',	
	TEXT_SURE_DELETE_ADDRESS: 'Вы действительно хотите удалить этот адрес',
	TEXT_ENTER_A_ADDRESS: 'Введите новый адрес',
	TEXT_EDIT_ADDRESS: 'Редактировать информацию адреса',
	TEXT_PLEASEENTER_CHARLEAST_2: 'Пожалуйста, введите 1 продукты по крайней мере.',
	TEXT_PLEASEENTER_CHARLEAST_5: 'Пожалуйста, введите 5 продукты по крайней мере.',
	TEXT_PLEASEENTER_CHARLEAST_3: 'Пожалуйста, введите 3 продукты по крайней мере.',
	TEXT_PLEASEENTER_RIGHTSTATE: 'Пожалуйста, введите правильную  Страну / провинцию / область.',
	ENTRY_FL_NAME_SAME_ERROR: 'Фамилия совпадает с именем. Пожалуйста, измените его.',
	ENTRY_FS_ADDRESS_SAME_ERROR:'Мы заметили, что ваш Адрес строки 2 такой же, как Адресная строка 1, пожалуйста, переписывайте Адресную строку 2 или просто оставляйте её пустой.',	
	TextYes:'Yes',
	TextNo:'No',	
    TEXT_CHECK_URL:'Введенный вами контент содержит нелегальные ссылки. Пожалуйста, исправьте это.',

	// oem
	'TEXT_FILE_FOEMAT_NOT_SUPPORTED': 'Формат файла не принят (Только png, jpg,jpeg, bmp, gif, doc, docx допускается)',
	'TEXT_PRODUCT_NAME_OR_LINK':'Продукции Название / Ссылка',
	'TEXT_WHY_DO_YOU_WANT_TO_BUY':'Что вы хотите купить?',
	'TEXT_WRONG_PRODUCT_NAME':'Пожалуйста, введите продукции Название / Ссылка.',
	'TEXT_ENTER_PRODUCT_OF_YOU_WANT':'Пожалуйста, введите подробную информацию о товаре, который вы хотите купить.',
	//'TEXT_FORMAT_ONLY_ACCEPT':'Format only Accept: png、jpg、jpeg、bmp、gif、doc、docx.',
	'TEXT_ONLY_THREE_FILE_AT_MOST':'Только 3 файлов на большинство может быть отображен.',
	//'TEXT_FILE_NO_MORE_THAN_TWO_M':'One file should be no more than 2MB.',
	'TEXT_EMAIL_REQUIRED':'ваш адрес электронной почты требуется писать.',
	'TEXT_INVALID_EMAIL':'Недействующая почта.',
	'TEXT_ERROR_EMAIL':'Неправильная  Электронная Почта.',
	'TEXT_ENTER_YOUR_NAME':'Пожалуйста, введите ваше имя, чтобы облегчить наше общение.',
	'TEXT_REMOVE':'Удалять',
	'TEXT_PRODUCT_NAME':'Наименование товаров',
	'TEXT_PRODUCT_NAME_OR_LINK':'Продукции Название / Ссылка',
	'TEXT_ENTER_A_COUPON_CODE':'Eввозите код купона',

	// index mailchimp
	'TEXT_SUBSCRIBR_SUCCESS': 'Спасибо за подписку!',

	// account edit
	'TEXT_LANG_YEAR': 'Года',
	'TEXT_LANG_MONTH': 'Месяц',
	'TEXT_LANG_DAY': 'День',

	'TEXT_UPLOAD_EXCEL_ERROR_TIPS': 'Принимать только формат: .xlsx, .xls. Один файл должен быть не более 2MB.',

	'TEXT_PAYPAL_WINDOW_TITLE':'No secure PayPal browser was found? We will help you restart the window to complete the payment.',
	'TEXT_PAYPAL_CONTINUE':'Continue'
};

