<?php
$order_status_config=array(
					array('EMAIL_SEPARATOR'=>'------------------------------------------------------',
						  'EMAIL_TEXT_ORDER_NUMBER'=>'Order Number:',
						  'EMAIL_TEXT_INVOICE_URL'=>'Detailed Invoice:',
						  'EMAIL_TEXT_DATE_SHIPPED'=>'Date Shipped:',
						  'EMAIL_TEXT_DATE_ORDERED'=>'Date Ordered:',
						  'EMAIL_TEXT_STATUS_UPDATED'=>'Your order has been updated to the following status:' . "\n",
						  'EMAIL_TEXT_STATUS_LABEL'=>'<strong>New status:</strong> %s' . "\n\n",
						  'EMAIL_TEXT_STATUS_PLEASE_REPLY'=>'Please reply to this email if you have any questions.' . "\n",
						  'TEXT_DEAR_WORDS'=>'Dear',
						  'EMAIL_TEXT_SUBJECT'=>'Order Update',
						  'EMAIL_NOTIFICATIONS_FROM'=>'notification@doreenbeads.com',
						  'STORE_NAME'=>'DoreenBeads.com',
						  'EMAIL_FOOTER_COPYRIGHT'=>'Copyright (c) ' . date('Y') . ' <a href="http://www.doreenbeads.com/" target="_blank">DoreenBeads</a>. Powered by <a href="http://www.doreenbeads.com/" target="_blank">DoreenBeads</a>',
						  'EMAIL_DISCLAIMER'=>'This email address was given to us by you or by one of our customers. If you feel that you have received this email in error, please send an email to %s',
					      'EMAIL_SPAM_DISCLAIMER'=>'This e-mail is sent in accordance with the US CAN-SPAM Law in effect 01/01/2004. Removal requests can be sent to this address and will be honored and respected.'
						  ),
					array('EMAIL_SEPARATOR'=>'------------------------------------------------------',
						  'EMAIL_TEXT_ORDER_NUMBER'=>'Bestellnummer:',
						  'EMAIL_TEXT_INVOICE_URL'=>'Detaillierte Rechnung:',
						  'EMAIL_TEXT_DATE_SHIPPED'=>'Versanddatum:',
						  'EMAIL_TEXT_DATE_ORDERED'=>'Datum der Bestellung:',
						  'EMAIL_TEXT_STATUS_UPDATED'=>'Ihr Bestellstatus wurde aktualisiert.' . "\n\n",
						  'EMAIL_TEXT_STATUS_LABEL'=>'<strong>Neuer Status:</strong> %s' . "\n\n",
						  'EMAIL_TEXT_STATUS_PLEASE_REPLY'=>'Bitte beantworten Sie diese E-Mail, wenn Sie irgendeine Frage haben.'. "\n",
						  'EMAIL_GREET_MR'=>'Sehr geehrter Herr %s' . "\n\n",
						  'EMAIL_GREET_MS'=>'Sehr geehrte Frau %s' . "\n\n",
						  'TEXT_DEAR_WORDS'=>'Liebe',
						  'EMAIL_TEXT_SUBJECT'=>'Bestellstatus aktualisiert',
						  'EMAIL_NOTIFICATIONS_FROM'=>'notification_de@doreenbeads.com',
						  'STORE_NAME'=>'DoreenBeads.com',
						  'EMAIL_FOOTER_COPYRIGHT'=>'Copyright (c) ' . date('Y') . ' <a href="http://www.doreenbeads.com/" target="_blank">DoreenBeads</a>. Powered by <a href="http://www.doreenbeads.com/" target="_blank">DoreenBeads</a>',
						  'EMAIL_DISCLAIMER'=>'Diese E-Mail Adresse wurde uns von Ihnen oder einer unserer Kunden mitgeteilt. Sollten Sie diese Nachricht versehentlich erhalten haben, wenden Sie sich bitte an %s',
						  'EMAIL_SPAM_DISCLAIMER'=>'Dieses Email ist gemäß dem USCAN-SPAM Gesetz in Kraft  01/01/2004 gesendet.Forderungen vom Abbestellen können an diese Adress geschickt werden und werden geehrt und aufgenommen.'
						  
					),
					array('EMAIL_TEXT_COMMENTS_UPDATE'=>'<em>Комментарии по Вашему заказу:<br /> </em>',
						  'EMAIL_TEXT_ORDER_NUMBER'=>'Номер заказа:',
						  'EMAIL_TEXT_INVOICE_URL'=>'Подробный счёт:',
						  'EMAIL_TEXT_DATE_SHIPPED'=>'Отправленная дата:',
						  'EMAIL_TEXT_DATE_ORDERED'=>'Заказанная дата:',
						  'EMAIL_TEXT_STATUS_UPDATED'=>'Ваш заказ был обновлен к следующему статусу:' . "\n",
						  'EMAIL_TEXT_STATUS_LABEL'=>'<strong>Новый статус:</strong> %s' . "\n\n",
						  'EMAIL_TEXT_STATUS_PLEASE_REPLY'=>'Пожалуйста, ответьте на это письмо, если у вас есть какие-либо вопросы.' . "\n",
						  'TEXT_DEAR_WORDS'=>'Здравствуйте ',
						  'EMAIL_TEXT_SUBJECT'=>'Обновление заказа',
						  'EMAIL_NOTIFICATIONS_FROM'=>'notification_ru@doreenbeads.com',
						  'STORE_NAME'=>'DoreenBeads.com',
						  'EMAIL_FOOTER_COPYRIGHT'=>'Авторское право (c) ' . date('Y') . ' <a href="http://www.doreenbeads.com/" target="_blank">DoreenBeads</a>. Поддержан <a href="http://www.doreenbeads.com/" target="_blank">DoreenBeads</a>',
						  'EMAIL_DISCLAIMER'=>'Этот адрес электронной почты был дан нам Вами или одним из наших клиентов. Если Вы чувствуете, что получили это электронное письмо по ошибке, пожалуйста, отправьте письмо на %s',
					      'EMAIL_SPAM_DISCLAIMER'=>'Это электронное письмо послано в соответствии с американским Законом МОЧЬ-СПАМА в действительности 01/01/2004. Запросы удаления можно послать в этот адрес и будут соблюдать и уважать.'
						  
							
					),
					array('EMAIL_TEXT_COMMENTS_UPDATE'=>'<em>Les commentaries sur votre commande sont:<br /> </em>',
						  'EMAIL_TEXT_ORDER_NUMBER'=>'Numéro de la commande:',
						  'EMAIL_TEXT_INVOICE_URL'=>'Facture détaillée:',
						  'EMAIL_TEXT_DATE_SHIPPED'=>'La date de livraison:',
						  'EMAIL_TEXT_DATE_ORDERED'=>'Date de passer la commande:',
						  'EMAIL_TEXT_STATUS_UPDATED'=>'Votre commande a été mise à jour comme l\’état suivant:' . "\n",
						  'EMAIL_TEXT_STATUS_LABEL'=>'<strong>Nouveau état:</strong> %s' . "\n\n",
			 			  'EMAIL_TEXT_STATUS_PLEASE_REPLY'=>'Répondez à cet email si vous avez des questions.' . "\n",
						  'TEXT_DEAR_WORDS'=>'Cher',
						  'EMAIL_TEXT_SUBJECT'=>'La mise à jour de la commande',
						  'EMAIL_NOTIFICATIONS_FROM'=>'notification_fr@doreenbeads.com',
						  'STORE_NAME'=>'DoreenBeads.com',
						  'EMAIL_FOOTER_COPYRIGHT'=>'Copyright (c) ' . date('Y') . ' <a href="http://www.doreenbeads.com/" cible="blanche">DoreenBeads</a>. Effectué par <a href="http://www.doreenbeads.com/" cible="blanche">DoreenBeads</a>',
						  'EMAIL_DISCLAIMER'=>'Cette adresse d\’e-mail nous est offert par vous ou un de nos clients. Si vous pensez que vous avez reçu ce message par erreur, veuillez nous envoyez un message à %.',
					      'EMAIL_SPAM_DISCLAIMER'=>'Cet e-mail est envoyé en fonction du loi US CAN-SPAM qui est mis en vigueur en le premierjour de l\’année 2004. Les exigences d\’annuler le message peuvent être envoyés à cette adresse et seront honorés et respectés.',
						  
					)
				);