<?php
define ( 'MODULE_PAYMENT_WESTERNUNION_TEXT_RECEIVER', '受取人 ' );
define ( 'MODULE_PAYMENT_WESTERNUNION_TEXT_SENDER', '差出人 ' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_MCTN', 'MTCN： ' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_AMOUNT', '金額：' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_CURRENCY', '通貨： ' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_FIRST_NAME', '名前： ' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_LAST_NAME', '苗字： ' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_ADDRESS', 'アドレス： ' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_ZIP', '郵便番号：' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_CITY', '都市： ' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_COUNTRY', '国名：' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_PHONE', '電話番号：' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_QUESTION', '質問： ' );
define ( 'MODULE_PAYMENT_WESTERNUNION_ENTRY_ANSWER', '回答：' );

define ( 'MODULE_PAYMENT_WEBMONEY_RECEIVER_FIRST_NAME', 'gc cc' );
define ( 'MODULE_PAYMENT_WESTERNUNION_RECEIVER_LAST_NAME', '' );
define ( 'MODULE_PAYMENT_WESTERNUNION_RECEIVER_ADDRESS', '' );
define ( 'MODULE_PAYMENT_WESTERNUNION_RECEIVER_ZIP', '' );
define ( 'MODULE_PAYMENT_WESTERNUNION_RECEIVER_CITY', '' );
define ( 'MODULE_PAYMENT_WESTERNUNION_RECEIVER_COUNTRY', '' );
define ( 'MODULE_PAYMENT_WESTERNUNION_RECEIVER_PHONE', '' );

define ( 'MODULE_PAYMENT_WEBMONEY_TEXT_HEAD', '<strong>ウェブマネー</strong>' );
define ( 'MODULE_PAYMENT_WEBMONEY_TEXT_DESCRIPTION', 'ウェブマネー' );

define ( 'MODULE_PAYMENT_WEBMONEY_TEXT_DESCRIPTION_CHECKOUT', '&bull; インターネットビジネスのスマートなソリューション。
																<br/>&bull; この多機能お支払いツールはオンラインでセキュリティと即時取引を提供します。
																<br/>&bull; ウェブマネーはRUB、ドル、ユーロの貨幣をサポートしています。 ' );
?>
