<?php
define('MODULE_SHIPPING_KDFEDEX_TEXT_TITLE', 'KD- FedEx');
define('MODULE_SHIPPING_KDFEDEX_TEXT_DESCRIPTION', '(7-8 días laborales para el envío)');
define('MODULE_SHIPPING_KDFEDEX_TEXT_WAY', TEXT_SHIPPING_TO);
define('MODULE_SHIPPING_KDFEDEX_TEXT_UNITS', TEXT_WEIGHT_KG);
define('MODULE_SHIPPING_KDFEDEX_INVALID_ZONE', TEXT_NO_SHIPPING_WORDS);
define('MODULE_SHIPPING_KDFEDEX_UNDEFINED_RATE', TEXT_SHIPPING_CANNOT_ARRIVE);
define('MODULE_SHIPPING_KDFEDEX_NOTE', sprintf(TEXT_SHIPPING_NOTE,'KDFEDEX'));
define('MODULE_SHIPPING_NORMAL_KDFEDEX_NOTE', sprintf(TEXT_SHIPPING_NOTE,'DHL'));
define('MODULE_SHIPPING_KDFEDEX_TEXT_ERROR', TEXT_ERROR_TO_CONTACT_US);
define('MODULE_SHIPPING_NORMAL_KDFEDEX_VOLUME_NOTE', TEXT_SHIPPING_FEE.', 
 			<a href="'.HTTP_SERVER.'/page.html?chapter=0&id=92" target="_blank">'.TEXT_CLICK_HERE_FOR_MORE.'.</a>');
?>