<?php
define('MODULE_SHIPPING_ZYFEDEX_TEXT_TITLE', 'ZY-Fedex');
define('MODULE_SHIPPING_ZYFEDEX_TEXT_DESCRIPTION', 'ZY-Fedex (7-8 días laborales para el envío)');
define('MODULE_SHIPPING_ZYFEDEX_TEXT_WAY', TEXT_SHIPPING_TO);
define('MODULE_SHIPPING_ZYFEDEX_TEXT_UNITS', TEXT_WEIGHT_KG);
define('MODULE_SHIPPING_ZYFEDEX_INVALID_ZONE', TEXT_NO_SHIPPING_WORDS);
define('MODULE_SHIPPING_ZYFEDEX_UNDEFINED_RATE', TEXT_SHIPPING_CANNOT_ARRIVE);
define('MODULE_SHIPPING_ZYFEDEX_NOTE', sprintf(TEXT_SHIPPING_NOTE,'ZY-Fedex'));
define('MODULE_SHIPPING_NORMAL_ZYFEDEX_NOTE', sprintf(TEXT_SHIPPING_NOTE,'ZY-Fedex'));
define('MODULE_SHIPPING_ZYFEDEX_TEXT_ERROR', TEXT_ERROR_TO_CONTACT_US);
define('MODULE_SHIPPING_NORMAL_ZYFEDEX_VOLUME_NOTE', TEXT_SHIPPING_FEE.', 
 			<a href="'.HTTP_SERVER.'/page.html?chapter=0&id=92" target="_blank">'.TEXT_CLICK_HERE_FOR_MORE.'.</a>');
?>