<?php
define('MODULE_ORDER_TOTAL_BALANCE_CASH_ACCOUNT_TITLE', 'Saldo Acreedor');
define('MODULE_ORDER_TOTAL_CASH_ACCOUNT_HEADER', 'Saldo Acreedor');
define('MODULE_ORDER_TOTAL_CASH_ACCOUNT_DESCRIPTION', 'Saldo Acreedor');
define('MODULE_ORDER_TOTAL_DEDUCTED_CASH_ACCOUNT_TITLE', 'Crédito actual Deducido');
?>