var $lang={
//errEnterKeywords: 'Entrer un mot clé ou un n°de réf', 
errEnterKeywords: 'Recherche des articles', 
errWrongEmail: 'Le format de l’adresse e-mail est incorrect, veuillez remplir l’adresse e-mail correcte.', 
errPassword: "Cela devrait être d’au moins 5 caractères (doit contenir des lettres et des chiffres).",  
errNotAgree: 'Vous n’acceptez pas les Termes et Conditions de Doreenbeads.com', 
errEmailContain: 'Adresse e-mail non valable. Il doit contenir au moins 6 caractères. Veuillez réessayer.', 
errRemoteCheck: 'Adresse email invalid. Veuillez saisir une adresse email valide.',
errConfirmPassword: 'La confirmation de mot de passe doit correspondre à votre mot de passe.', 
errEnter2Char: 'Veuillez entrer au moins 1 caractères', 
ReviewTips: 'Je vous en prie ajouter quelques mots à vos commentaires. le réexamen doit avoir au moins 1 caractère.', 
InputValidCode: 'Veuillez saisir un code bien valide!', 
EnterEmailAddress: 'Veuillez saisir votre adresse E-mail', 
CheckEmailAddress: 'Veuillez vérifier votre adresse E-mail', 
EnterName: 'Veuillez entrer votre nom', 
EnterFriendEmail: "Veuillez saisir l’adresse E-mail de votre ami(e)", 
CheckFriendEmail: "Veuillez verifer l’adresse E-mail de votre ami(e), il faut comme ça email@hotmail.com", 
CheckYourEmail: 'Veuillez verifer l’adresse E-mail de votre ami(e)s, il faut comme ça email@hotmail.com', 
EnterFriendName: "Veuillez entrer le nom de votre ami(e)", 
EnterFirstName: 'Veuillez taper votre prénom (au moins 1 caractère).', 
EnterLastName: 'Veuillez taper votre nom (au moins 1 caractère).', 
ReviewLevel: ["(Mal)","(Moyen)","(Bien)","(Très Bien)","(Excellent)"],
ChooseRating: '*Veuillez laisser une évaluation pour cet objet', 
SuccessAddcart: 'Article(s) ajouté(s) avec succès à votre panier!<br/><a href="index.php?main_page=shopping_cart">Voir le panier</a>', 
TextUpdate: 'Mettre à jour', 
QtyAlreadyInCart: 'Quantité déjà dans votre panier: ', 
SuccessAddWishlist: 'Article(s) ajouté(s) avec succès à votre liste favorite!<br/><a href="index.php?main_page=wishlist">Voir les produits dans le wishlist</a>', 
HasInWishlist: 'Cet article est déjà dans votre liste favorite.<br/><a href="index.php?main_page=wishlist">Voir les produits dans le wishlist</a>', 
LoginToOperation: 'Veuillez vous connecter pour l’opération <a href="index.php?main_page=login">Login</a>', 
SuccessSubscribed: 'Félicitation! Vous êtes inscrit avec succès à la notification du rapprovisionnement de cet article  Un e-mail avec le lien de cet article vous sera envoyé dès que le stock est disponible.', 
EnterRightQty: 'Veuillez entrer une quantité valide!', 
QtyInCart: 'Quantité dans le Panier', 
ErrorPleaseKeyword: 'Veuillez saisir un mot-clé ou le N°de réf.',
ENTER_PASSWORD_PROMPT : 'Veuillez saisir votre mot de passe.',
TEXT_CONFIRM_PASSWORD : "N’oubliez pas de re-taper votre mot de passe!",
CHECKOUT_ZIP_CODE_ERROR:'Veuillez vérifier votre code postal. Le format correct(p. ex.):',
TEXT_OR:'ou', 
CartAreYouSureInvaild:'Confirmez-vous de vider les articles invalides?',
CartAreYouSureDelete: 'Est-ce que vous êtes sûr de supprimer cet article?',
CartAreYouSureDeleteAll: 'Confirmez-vous la suppression des articles sélectionnés dans le panier?',
CartJsWrongNumber: 'Le N°de réf est incorrect. Pour continuer, vous devez retirer cet article de votre liste.',
CartWrongNumber: 'Le N°de réf est incorrect.',
CartJsNoStock: 'En rupture de stock. Pour continuer, vous devez retirer cet article de votre liste.',
CartNoStock: 'En rupture de stock',
CartQuickAddWrong: 'Désolé, certain d’articles sont indisponibles. Veuillez retirer le N°de réf / quantité incorrecte',
CartQuickAddEmpty: 'Veuillez entrer au moins un Product No. et la quantité',

TextProcess: 'Traitement...',
TEXT_SURE_DELETE_ADDRESS: 'Etes-vous sûr de supprimer cette adresse?',
TEXT_ENTER_A_ADDRESS: 'Entrez une nouvelle adresse',
TEXT_EDIT_ADDRESS: 'Modifier l’information d’adresse',
TEXT_PLEASEENTER_CHARLEAST_2: 'Veuillez entrer au moins 1 caractères.',
TEXT_PLEASEENTER_CHARLEAST_5: 'Veuillez entrer au moins 5 caractère.',
TEXT_PLEASEENTER_CHARLEAST_3: 'Veuillez entrer au moins 3 caractère.',
TEXT_PLEASEENTER_RIGHTSTATE: 'Veuillez entrer votre pays​​/ province/ région correcte.',
ENTRY_FL_NAME_SAME_ERROR: 'Vous avez le même nom et prénom, veuillez le modifier.',
ENTRY_FS_ADDRESS_SAME_ERROR:"Nous avons remarqué que votre adresse ligne 2 est même que l’adresse ligne 1 , veuillez réécrire l’adresse ligne 2 ou le laisser vide.",	
TextYes:'Oui',
TextNo:'Non',
TEXT_CHECK_URL:'Il y a un lien illégal dans le contenu que vous avez entré. Veuillez le corriger.',

// oem
'TEXT_FILE_FOEMAT_NOT_SUPPORTED': 'Le format de fichier n’est pas acceptable. (Seulement png, jpg,jpeg, bmp, gif, doc, docx permis) ',
'TEXT_PRODUCT_NAME_OR_LINK':'Nom /Lien du Produit',
'TEXT_WHY_DO_YOU_WANT_TO_BUY':'Que voulez-vous acheter?',
'TEXT_WRONG_PRODUCT_NAME':'Veuillez entrer le Nom / le Lien du produit.',
'TEXT_ENTER_PRODUCT_OF_YOU_WANT':'Veuillez entrer les détails du produit que vous voulez acheter.',
//'TEXT_FORMAT_ONLY_ACCEPT':'Format only Accept: png、jpg、jpeg、bmp、gif、doc、docx.',
'TEXT_ONLY_THREE_FILE_AT_MOST':'Seulement trois fichiers tout au plus peuvent être affichés.',
//'TEXT_FILE_NO_MORE_THAN_TWO_M':'One file should be no more than 2MB.',
'TEXT_EMAIL_REQUIRED':'Votre adresse e-mail est nécessaire.',
'TEXT_INVALID_EMAIL':'Email Non-valable.',
'TEXT_ERROR_EMAIL':'Erreur d\'Email',
'TEXT_ENTER_YOUR_NAME':'Veuillez entrer votre nom pour faciliter notre communication.',		
'TEXT_REMOVE':'supprimer',
'TEXT_PRODUCT_NAME':'Nom de Produit',
'TEXT_PRODUCT_NAME_OR_LINK':'Nom /Lien du Produit',

'TEXT_ENTER_A_COUPON_CODE':'Enter un code de coupon',

// index mailchimp
'TEXT_SUBSCRIBR_SUCCESS': 'Merci pour votre enregistrement!',

// account edit
'TEXT_LANG_YEAR': 'Année',
'TEXT_LANG_MONTH': 'Mois',
'TEXT_LANG_DAY': 'Jour',

'TEXT_UPLOAD_EXCEL_ERROR_TIPS': 'Format uniquement acceptez: .xlsx, .xls. Un fichier ne doit pas dépasser 2 MB.',

'TEXT_PAYPAL_WINDOW_TITLE':'Vous n’avez pas trouvé de navigateur PayPal sécurisé? Nous vous aiderons à redémarrer la fenêtre pour terminer le paiement.',
'TEXT_PAYPAL_CONTINUE':'Continuer'
};