<?php
define ( 'MODULE_SHIPPING_CHINAPOST_TEXT_TITLE', 'EMSエクスプレス' );
define ( 'MODULE_SHIPPING_CHINAPOST_TEXT_DESCRIPTION', 'EMSエクスプレス' );
// define('MODULE_SHIPPING_CHINAPOST_TEXT_DESCRIPTION', 'China Post Domestic and International EMS (Express Mail Service)');
define ( 'MODULE_SHIPPING_CHINAPOST_TEXT_WAY', TEXT_SHIPPING_TO );
define ( 'MODULE_SHIPPING_CHINAPOST_TEXT_UNITS', TEXT_WEIGHT_KG );
define ( 'MODULE_SHIPPING_CHINAPOST_INVALID_ZONE', TEXT_NO_SHIPPING_WORDS );
define ( 'MODULE_SHIPPING_CHINAPOST_UNDEFINED_RATE', TEXT_SHIPPING_CANNOT_ARRIVE );
define ( 'MODULE_SHIPPING_CHINAPOST_TEXT_ERROR', TEXT_ERROR_TO_CONTACT_US );
define ( 'MODULE_SHIPPING_CHINAPOST_VOLUME_NOTE', TEXT_SHIPPING_FEE . ',
			<a href="' . HTTP_SERVER . '/page.html?chapter=0&id=92" target="_blank">' . TEXT_CLICK_HERE_FOR_MORE . '.</a>' );
?>
