<?php
define('MODULE_SHIPPING_HMFREXPR_TEXT_TITLE', 'Línea de Expreso Francés');
define('MODULE_SHIPPING_HMFREXPR_TEXT_DESCRIPTION', 'Línea de Expreso Francés');
define('MODULE_SHIPPING_HMFREXPR_SHIPPING_DAYS', '');
define('MODULE_SHIPPING_HMFREXPR_INVALID_ZONE', TEXT_NO_SHIPPING_WORDS);
define('MODULE_SHIPPING_HMFREXPR_VOLUME_NOTE', TEXT_SHIPPING_FEE.', <a href="'.HTTP_SERVER.'/page.html?chapter=0&id=92" target="_blank">'.TEXT_CLICK_HERE_FOR_MORE.'.</a>');
?>