<?php
define('MODULE_SHIPPING_PERWEIGHTUNIT_TEXT_TITLE', 'Por Unidad');
define('MODULE_SHIPPING_PERWEIGHTUNIT_TEXT_DESCRIPTION', 'Por Unidad');
define('MODULE_SHIPPING_PERWEIGHTUNIT_TEXT_WAY', 'La Menjor Manera');
?>