<?php
define('MODULE_SHIPPING_HMDPD_TEXT_TITLE', 'Servicio de DPD Express');
define('MODULE_SHIPPING_HMDPD_TEXT_DESCRIPTION', 'Servicio de DPD Express');
define('MODULE_SHIPPING_HMDPD_TEXT_WAY', TEXT_SHIPPING_TO);
define('MODULE_SHIPPING_HMDPD_TEXT_UNITS', TEXT_WEIGHT_KG);
define('MODULE_SHIPPING_HMDPD_INVALID_ZONE', TEXT_NO_SHIPPING_WORDS);
define('MODULE_SHIPPING_HMDPD_UNDEFINED_RATE', TEXT_SHIPPING_CANNOT_ARRIVE);
define('MODULE_SHIPPING_HMDPD_REMOTE_NOTE', sprintf(TEXT_SHIPPING_NOTE,'DPD'));
define('MODULE_SHIPPING_HMDPD_VOLUME_NOTE', TEXT_SHIPPING_FEE.', 				<a href="'.HTTP_SERVER.'/page.html?chapter=0&id=92" target="_blank">'.TEXT_CLICK_HERE_FOR_MORE.'.</a>');
?>