<?php
define ( 'MODULE_SHIPPING_PERWEIGHTUNIT_TEXT_TITLE', '単位ごとに' );
define ( 'MODULE_SHIPPING_PERWEIGHTUNIT_TEXT_DESCRIPTION', '単位ごとに' );
define ( 'MODULE_SHIPPING_PERWEIGHTUNIT_TEXT_WAY', '最良の方法' );
?>
